class DetailsAnimator{constructor(){this.isChildAnimating=false;this.init();this.preventDoubleTap();}
init(){if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',()=>this.setupDetails());}else{this.setupDetails();}}
setupDetails(){const detailsElements=document.querySelectorAll('details');detailsElements.forEach(details=>{this.wrapDetailsContent(details);this.setupSummaryClick(details);this.initializeDetailsState(details);});setTimeout(()=>this.animateButtons(),100);this.setupEscapeHandler();}
wrapDetailsContent(details){const summary=details.querySelector('summary');const contentElements=[];Array.from(details.children).forEach(child=>{if(child!==summary&&!child.classList.contains('details-content')){contentElements.push(child);}});if(details.querySelector('.details-content'))return;if(contentElements.length>0){const contentWrapper=document.createElement('div');contentWrapper.className='details-content';if(!details.open){contentWrapper.style.maxHeight='0';contentWrapper.style.opacity='0';}else{contentWrapper.style.maxHeight='none';contentWrapper.style.opacity='1';}
contentElements.forEach(element=>{contentWrapper.appendChild(element);});summary.insertAdjacentElement('afterend',contentWrapper);}}
initializeDetailsState(details){if(details.open){details.classList.add('open');const contentWrapper=details.querySelector('.details-content');if(contentWrapper){contentWrapper.style.maxHeight='none';contentWrapper.style.opacity='1';}}else{details.classList.remove('open');const contentWrapper=details.querySelector('.details-content');if(contentWrapper){contentWrapper.style.maxHeight='0';contentWrapper.style.opacity='0';}}}
setupSummaryClick(details){const summary=details.querySelector('summary');summary.addEventListener('click',(e)=>{e.preventDefault();if(details.classList.contains('animating'))return;const isOpening=!details.open;details.classList.add('animating');if(isOpening){details.open=true;details.classList.add('open');this.animateContentIn(details);setTimeout(()=>{details.classList.remove('animating');},400);}else{this.closeAllChildDetails(details);details.classList.remove('open');this.animateContentOut(details);setTimeout(()=>{details.open=false;details.classList.remove('animating');},350);}
setTimeout(()=>this.animateButtons(),100);});}
animateContentIn(details){const contentWrapper=details.querySelector('.details-content');if(!contentWrapper)return;contentWrapper.style.maxHeight='0';contentWrapper.style.opacity='0';requestAnimationFrame(()=>{const contentHeight=contentWrapper.scrollHeight;contentWrapper.style.maxHeight=contentHeight+'px';contentWrapper.style.opacity='1';setTimeout(()=>{if(details.open){contentWrapper.style.maxHeight='none';}},400);});this.animateChildElements(details,true);}
animateContentOut(details){const contentWrapper=details.querySelector('.details-content');if(!contentWrapper)return;const contentHeight=contentWrapper.scrollHeight;contentWrapper.style.maxHeight=contentHeight+'px';contentWrapper.style.opacity='1';requestAnimationFrame(()=>{contentWrapper.style.maxHeight='0';contentWrapper.style.opacity='0';});this.animateChildElements(details,false);}
closeAllChildDetails(parentDetails){const childDetails=parentDetails.querySelectorAll('details');childDetails.forEach(childDetail=>{if(childDetail.open||childDetail.classList.contains('open')){childDetail.classList.remove('open');childDetail.open=false;const childContent=childDetail.querySelector('.details-content');if(childContent){childContent.style.maxHeight='0';childContent.style.opacity='0';}
this.closeAllChildDetails(childDetail);}});}
animateChildElements(details,show){const lists=details.querySelectorAll('ul');lists.forEach(list=>{if(show){list.style.opacity='1';list.style.transform='translateY(0)';}else{list.style.opacity='0';list.style.transform='translateY(-5px)';}});const listItems=details.querySelectorAll('li');listItems.forEach((item,index)=>{if(show){item.style.opacity='1';item.style.transform='translateY(0)';}else{item.style.opacity='0';item.style.transform='translateY(10px)';}});const tables=details.querySelectorAll('.table-container');tables.forEach(table=>{if(show){table.style.opacity='1';table.style.transform='translateY(0)';}else{table.style.opacity='0';table.style.transform='translateY(10px)';}});const tableRows=details.querySelectorAll('tbody tr');tableRows.forEach((row,index)=>{if(show){row.style.opacity='1';row.style.transform='translateX(0)';}else{row.style.opacity='0';row.style.transform='translateX(-10px)';}});const infoMissing=details.querySelectorAll('.info-missing');infoMissing.forEach(info=>{if(show){info.style.opacity='1';info.style.transform='scale(1)';}else{info.style.opacity='0';info.style.transform='scale(0.95)';}});}
animateButtons(){const buttons=document.querySelectorAll('.button:not(.visible)');buttons.forEach((button)=>{setTimeout(()=>{button.classList.add('visible');},50+100);});}
setupEscapeHandler(){document.addEventListener('keydown',(e)=>{if(e.key==='Escape'){this.closeAllOpenDetails();}});}
closeAllOpenDetails(){const openDetails=document.querySelectorAll('details[open], details.open');openDetails.forEach(details=>{if(details.classList.contains('animating'))return;details.classList.add('animating');this.closeAllChildDetails(details);details.classList.remove('open');this.animateContentOut(details);setTimeout(()=>{details.open=false;details.classList.remove('animating');},350);});}
preventDoubleTap(){let lastTouchEnd=0;document.addEventListener('touchend',function(event){const now=(new Date()).getTime();if(now-lastTouchEnd<=300){event.preventDefault();}
lastTouchEnd=now;},false);document.addEventListener('contextmenu',function(e){if(e.target.classList.contains('button')||e.target.tagName==='SUMMARY'){e.preventDefault();}});document.querySelectorAll('a[href^="#"]').forEach(anchor=>{anchor.addEventListener('click',function(e){e.preventDefault();const target=document.querySelector(this.getAttribute('href'));if(target){target.scrollIntoView({behavior:'smooth',block:'start'});}});});}}
let detailsAnimator;if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',()=>{detailsAnimator=new DetailsAnimator();});}else{detailsAnimator=new DetailsAnimator();}
if(typeof module!=='undefined'&&module.exports){module.exports=DetailsAnimator;}